### ISSUE TITLE
Cannot delete the last pool in a cluster

### ISSUE THREAD

**Issue by sergiorivera50** [symbiosis-cloud/terraform-provider-symbiosis#15] opened 2023-01-23 11:41 UTC
**Issue Description**

Terraform provider for Symbiosis is no longer able to destroy resources, with the error `Symbiosis: Cannot delete the last pool in a cluster (type=Bad Request, path=/rest/v1/node-pool/<pool-id>)`. This issue occurred after what seems to be an update of the backend API for Symbiosis. My configuration has not changed and previously worked without problems. It's worth mentioning that I have also updated the Terraform provider version.

My configuration is as follows:

```tf
provider "symbiosis" {
  api_key = var.symbiosis_api_key
}

resource "symbiosis_cluster" "cluster" {
  name = var.cluster_name
  region = "germany-1"
}

resource "symbiosis_node_pool" "node_pool" {
  cluster = symbiosis_cluster.cluster.name
  name = "testing-node-pool"
  node_type = "general-1"
  quantity = 3
}
```

This is causing an issue for me as I would like to be able to cleanup my resources directly from Terraform, instead of having to manually do it in the UI at `app.symbiosis.host/clusters/<cluster-id>`.

**Steps to Reproduce**

1. Create a cluster and node pool with the configuration above.
2. Attempt to destroy the resources with terraform destroy.
3. Observe the error `Symbiosis: Cannot delete the last pool in a cluster (type=Bad Request, path=/rest/v1/node-pool/<pool-id>)`.

**Expected behavior**

The resources should be successfully destroyed without errors.

**Environment**

Terraform version: v1.2.0 (on darwin_arm64)
Symbiosis provider version: 0.5.0

**Comment by Styren** [comment] 2023-01-23 11:46
Hey! Thanks for reporting this issue, it indeed looks like a regression. I'll have a look at it and get back to you.

**Comment by sergiorivera50** [comment] 2023-01-23 11:49
You guys have to be the team with the quickest replies from feedback.
Thanks! I'll be glad to help as much as I can.

**Comment by sergiorivera50** [comment] 2023-01-23 11:51
Just for the record, upgrading from Terraform v1.2.0 -> v1.3.7 didn't fix the problem.

**Comment by Styren** [comment] 2023-01-23 13:46
> You guys have to be the team with the quickest replies from feedback. Thanks! I'll be glad to help as much as I can.

Haha thank you 🙏 we do our best

> Just for the record, upgrading from Terraform v1.2.0 -> v1.3.7 didn't fix the problem.

Yes unfortunately it's a backend issue. We just pushed a change that should remove the error, I'll close the issue but please let me know if you're still running into any problems. 😊

**Closed as completed by Styren** 2023-01-23 13:46 UTC

**Comment by sergiorivera50** [comment] 2023-01-23 13:56
Great! I have successfully destroyed my cluster with Terraform now 😁

**Comment by Styren** [comment] 2023-01-23 14:03
> Great! I have successfully destroyed my cluster with Terraform now 😁

Perfect -- happy to hear that! :)
